INSERT INTO popular_quotes VALUES (1, 'Yoda', '“When nine hundred years old you reach, look as good you will not.” Return of the Jedi');
INSERT INTO popular_quotes VALUES (2, 'Yoda', '“Truly wonderful, the mind of a child is.” Attack of the Clones');
INSERT INTO popular_quotes VALUES (3, 'Yoda', '“That is why you fail.” The Empire Strikes Back');
INSERT INTO popular_quotes VALUES (4, 'Yoda', '“A Jedi uses the Force for knowledge and defense, never for attack.” The Empire Strikes Back');
INSERT INTO popular_quotes VALUES (5, 'Yoda', '“Adventure. Excitement. A Jedi craves not these things.” The Empire Strikes Back');
INSERT INTO popular_quotes VALUES (6, 'Yoda', '“Judge me by my size, do you?” The Empire Strikes Back');
INSERT INTO popular_quotes VALUES (7, 'Yoda', '“Fear is the path to the dark side…fear leads to anger…anger leads to hate…hate leads to suffering.” The Phantom Menace');
INSERT INTO popular_quotes VALUES (8, 'Yoda', '“Wars not make one great.” The Empire Strikes Back');
INSERT INTO popular_quotes VALUES (9, 'Yoda', '“Luminous beings are we…not this crude matter.” The Empire Strikes Back');
INSERT INTO popular_quotes VALUES (10, 'Yoda', '“Do. Or do not. There is no try.” The Empire Strikes Back');
INSERT INTO popular_quotes VALUES (11, 'Motivational', '“Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy.” — Norman Vincent Peale');
INSERT INTO popular_quotes VALUES (12, 'Motivational', '“If you can dream it, you can do it.” — Walt Disney');
INSERT INTO popular_quotes VALUES (13, 'Motivational', '“Press forward. Do not stop, do not linger in your journey, but strive for the mark set before you.” — George Whitefield');
INSERT INTO popular_quotes VALUES (14, 'Motivational', '“The future belongs to those who believe in the beauty of their dreams.” — Eleanor Roosevelt');
INSERT INTO popular_quotes VALUES (15, 'Motivational', '“Aim for the moon. If you miss, you may hit a star.” — W. Clement Stone');
INSERT INTO popular_quotes VALUES (16, 'Motivational', '“Don’t watch the clock; do what it does. Keep going.” — Sam Levenson');
INSERT INTO popular_quotes VALUES (17, 'Motivational', '“There will be obstacles. There will be doubters. There will be mistakes. But with hard work, there are no limits.” — Michael Phelps');
INSERT INTO popular_quotes VALUES (18, 'Motivational', '“We aim above the mark to hit the mark.” — Ralph Waldo Emerson');
INSERT INTO popular_quotes VALUES (19, 'Motivational', '“Change your life today. Don’t gamble on the future, act now, without delay.” — Simone de Beauvoir');
INSERT INTO popular_quotes VALUES (20, 'Motivational', '“You just can’t beat the person who never gives up.” — Babe Ruth');
