server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/drazen-nikolic/spring-cloud-example.git
          search-paths: spring-cloud-quotes-app-config
      allow-override: true

   
      
