server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://git.seavus.com/opensource/spring-cloud-quotes-app-config.git
      allow-override: true

   
      
